cache: bundler
language: ruby
matrix:
  include:
    - rvm: ruby-head
    - rvm: 2.4.1
    - rvm: 2.4.0
    - rvm: 2.3.4
  allow_failures:
    - rvm: ruby-head
install:
  - bundle install --retry=3
script: bundle exec rake
