#!/usr/bin/env ruby
require_relative '../lib/whatis'
require_relative '../lib/whatis/cli'
require 'optparse'
require 'ostruct'

options = OpenStruct.new
options.language = 'en'
options.format = 'short'

parser = OptionParser.new do |opts|
  opts.banner = 'Usage: `whatis [options] title1, title2, title3'

  opts.separator ''
  opts.separator 'Options:'

  opts.on('-l', '--language CODE', 'Which language Wikipedia to ask, 2-letter code. "en" by default') do |lang|
    options.language = lang
  end

  opts.on('-t', '--languages [CODE]', 'Without argument, fetches all translations for entity. With argument (two-letter code) fetches only one translation') do |langs|
    options.languages = langs || true
  end

  opts.on('--categories', 'Whether to fetch entity categories') do
    options.categories = true
  end

  opts.on('-f', '--format FORMAT', %w[shot long json], 'Output format: one line per entity (short), several lines per entity (long), or JSON. Default is "short"') do |format|
    options.format = format
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end

parser.parse!(ARGV)

if ARGV.empty?
  puts parser
  exit
end

puts WhatIs::CLI.new(ARGV, options).run
